// Package router provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package router

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyScopes = "apiKey.Scopes"
)

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	CustomerName string   `json:"customerName"`
	Discount     *float64 `json:"discount,omitempty"`
	Items        []struct {
		ServiceId int `json:"serviceId"`
		WorkerId  int `json:"workerId"`
	} `json:"items"`
	PaymentMethodId int `json:"paymentMethodId"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Order defines model for Order.
type Order struct {
	CreatedAt         time.Time `json:"createdAt"`
	CustomerName      string    `json:"customerName"`
	Discount          float64   `json:"discount"`
	Id                int       `json:"id"`
	PaymentMethodId   int       `json:"paymentMethodId"`
	PaymentMethodName *string   `json:"paymentMethodName,omitempty"`
	Subtotal          float64   `json:"subtotal"`
	Tax               float64   `json:"tax"`
	TaxPercentage     float64   `json:"taxPercentage"`
	Total             float64   `json:"total"`
}

// OrderDetail defines model for OrderDetail.
type OrderDetail struct {
	CreatedAt         time.Time    `json:"createdAt"`
	CustomerName      string       `json:"customerName"`
	Discount          float64      `json:"discount"`
	Id                int          `json:"id"`
	Items             *[]OrderItem `json:"items,omitempty"`
	PaymentMethodId   int          `json:"paymentMethodId"`
	PaymentMethodName *string      `json:"paymentMethodName,omitempty"`
	Subtotal          float64      `json:"subtotal"`
	Tax               float64      `json:"tax"`
	TaxPercentage     float64      `json:"taxPercentage"`
	Total             float64      `json:"total"`
}

// OrderItem defines model for OrderItem.
type OrderItem struct {
	CommissionFee float64   `json:"commissionFee"`
	CreatedAt     time.Time `json:"createdAt"`
	Id            int       `json:"id"`
	ServiceId     int       `json:"serviceId"`
	ServiceName   string    `json:"serviceName"`
	ServicePrice  float64   `json:"servicePrice"`
	WorkerId      int       `json:"workerId"`
	WorkerName    string    `json:"workerName"`
}

// OrderSummary defines model for OrderSummary.
type OrderSummary struct {
	ByPaymentMethod *[]struct {
		OrderCount        *int     `json:"orderCount,omitempty"`
		PaymentMethodId   *int     `json:"paymentMethodId,omitempty"`
		PaymentMethodName *string  `json:"paymentMethodName,omitempty"`
		TotalRevenue      *float64 `json:"totalRevenue,omitempty"`
	} `json:"byPaymentMethod,omitempty"`
	From            *openapi_types.Date `json:"from,omitempty"`
	OrderCount      *int                `json:"orderCount,omitempty"`
	To              *openapi_types.Date `json:"to,omitempty"`
	TotalCommission *float64            `json:"totalCommission,omitempty"`
	TotalDiscount   *float64            `json:"totalDiscount,omitempty"`
	TotalRevenue    *float64            `json:"totalRevenue,omitempty"`
	TotalTax        *float64            `json:"totalTax,omitempty"`
}

// PaginatedResponse defines model for PaginatedResponse.
type PaginatedResponse struct {
	Limit *int `json:"limit,omitempty"`
	Page  *int `json:"page,omitempty"`
	Total *int `json:"total,omitempty"`
}

// PaymentMethod defines model for PaymentMethod.
type PaymentMethod struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// PaymentMethodRequest defines model for PaymentMethodRequest.
type PaymentMethodRequest struct {
	Name string `json:"name"`
}

// Service defines model for Service.
type Service struct {
	CategoryId   int     `json:"categoryId"`
	CategoryName *string `json:"categoryName,omitempty"`
	Id           int     `json:"id"`
	Name         string  `json:"name"`
	Price        float64 `json:"price"`
}

// ServiceCategory defines model for ServiceCategory.
type ServiceCategory struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// ServiceCategoryRequest defines model for ServiceCategoryRequest.
type ServiceCategoryRequest struct {
	Name string `json:"name"`
}

// ServiceRequest defines model for ServiceRequest.
type ServiceRequest struct {
	CategoryId int     `json:"categoryId"`
	Name       string  `json:"name"`
	Price      float64 `json:"price"`
}

// Worker defines model for Worker.
type Worker struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`
	Name      string    `json:"name"`
}

// WorkerCommissionSummary defines model for WorkerCommissionSummary.
type WorkerCommissionSummary struct {
	ByService *[]struct {
		Count           *int     `json:"count,omitempty"`
		ServiceId       *int     `json:"serviceId,omitempty"`
		ServiceName     *string  `json:"serviceName,omitempty"`
		TotalCommission *float64 `json:"totalCommission,omitempty"`
	} `json:"byService,omitempty"`
	From            *openapi_types.Date `json:"from,omitempty"`
	OrderCount      *int                `json:"orderCount,omitempty"`
	To              *openapi_types.Date `json:"to,omitempty"`
	TotalCommission *float64            `json:"totalCommission,omitempty"`
	WorkerId        *int                `json:"workerId,omitempty"`
	WorkerName      *string             `json:"workerName,omitempty"`
}

// WorkerRequest defines model for WorkerRequest.
type WorkerRequest struct {
	Name string `json:"name"`
}

// FromParam defines model for FromParam.
type FromParam = openapi_types.Date

// IdParam defines model for IdParam.
type IdParam = int

// LimitParam defines model for LimitParam.
type LimitParam = int

// PageParam defines model for PageParam.
type PageParam = int

// ToParam defines model for ToParam.
type ToParam = openapi_types.Date

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = Error

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	Page  *PageParam  `form:"page,omitempty" json:"page,omitempty"`
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// From Start date (inclusive), format YYYY-MM-DD
	From *FromParam `form:"from,omitempty" json:"from,omitempty"`

	// To End date (inclusive), format YYYY-MM-DD
	To *ToParam `form:"to,omitempty" json:"to,omitempty"`
}

// GetOrderSummaryParams defines parameters for GetOrderSummary.
type GetOrderSummaryParams struct {
	// From Start date (inclusive), format YYYY-MM-DD
	From *FromParam `form:"from,omitempty" json:"from,omitempty"`

	// To End date (inclusive), format YYYY-MM-DD
	To *ToParam `form:"to,omitempty" json:"to,omitempty"`
}

// ListPaymentMethodsParams defines parameters for ListPaymentMethods.
type ListPaymentMethodsParams struct {
	IsActive *bool `form:"isActive,omitempty" json:"isActive,omitempty"`
}

// DownloadOrderReportParams defines parameters for DownloadOrderReport.
type DownloadOrderReportParams struct {
	// From Start date (inclusive), format YYYY-MM-DD
	From *FromParam `form:"from,omitempty" json:"from,omitempty"`

	// To End date (inclusive), format YYYY-MM-DD
	To *ToParam `form:"to,omitempty" json:"to,omitempty"`
}

// ListServiceCategoriesParams defines parameters for ListServiceCategories.
type ListServiceCategoriesParams struct {
	IsActive *bool `form:"isActive,omitempty" json:"isActive,omitempty"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	CategoryId *int  `form:"categoryId,omitempty" json:"categoryId,omitempty"`
	IsActive   *bool `form:"isActive,omitempty" json:"isActive,omitempty"`
}

// ListWorkersParams defines parameters for ListWorkers.
type ListWorkersParams struct {
	IsActive *bool `form:"isActive,omitempty" json:"isActive,omitempty"`
}

// GetWorkerCommissionSummaryParams defines parameters for GetWorkerCommissionSummary.
type GetWorkerCommissionSummaryParams struct {
	// From Start date (inclusive), format YYYY-MM-DD
	From *FromParam `form:"from,omitempty" json:"from,omitempty"`

	// To End date (inclusive), format YYYY-MM-DD
	To *ToParam `form:"to,omitempty" json:"to,omitempty"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// CreatePaymentMethodJSONRequestBody defines body for CreatePaymentMethod for application/json ContentType.
type CreatePaymentMethodJSONRequestBody = PaymentMethodRequest

// UpdatePaymentMethodJSONRequestBody defines body for UpdatePaymentMethod for application/json ContentType.
type UpdatePaymentMethodJSONRequestBody = PaymentMethodRequest

// CreateServiceCategoryJSONRequestBody defines body for CreateServiceCategory for application/json ContentType.
type CreateServiceCategoryJSONRequestBody = ServiceCategoryRequest

// UpdateServiceCategoryJSONRequestBody defines body for UpdateServiceCategory for application/json ContentType.
type UpdateServiceCategoryJSONRequestBody = ServiceCategoryRequest

// CreateServiceJSONRequestBody defines body for CreateService for application/json ContentType.
type CreateServiceJSONRequestBody = ServiceRequest

// UpdateServiceJSONRequestBody defines body for UpdateService for application/json ContentType.
type UpdateServiceJSONRequestBody = ServiceRequest

// CreateWorkerJSONRequestBody defines body for CreateWorker for application/json ContentType.
type CreateWorkerJSONRequestBody = WorkerRequest

// UpdateWorkerJSONRequestBody defines body for UpdateWorker for application/json ContentType.
type UpdateWorkerJSONRequestBody = WorkerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List orders
	// (GET /orders)
	ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams)
	// Create order
	// (POST /orders)
	CreateOrder(w http.ResponseWriter, r *http.Request)
	// Get order aggregates
	// (GET /orders/summary)
	GetOrderSummary(w http.ResponseWriter, r *http.Request, params GetOrderSummaryParams)
	// Get order detail
	// (GET /orders/{id})
	GetOrder(w http.ResponseWriter, r *http.Request, id IdParam)
	// List payment methods
	// (GET /payment-methods)
	ListPaymentMethods(w http.ResponseWriter, r *http.Request, params ListPaymentMethodsParams)
	// Create payment method
	// (POST /payment-methods)
	CreatePaymentMethod(w http.ResponseWriter, r *http.Request)
	// Delete payment method
	// (DELETE /payment-methods/{id})
	DeletePaymentMethod(w http.ResponseWriter, r *http.Request, id IdParam)
	// Get payment method by ID
	// (GET /payment-methods/{id})
	GetPaymentMethod(w http.ResponseWriter, r *http.Request, id IdParam)
	// Update payment method
	// (PUT /payment-methods/{id})
	UpdatePaymentMethod(w http.ResponseWriter, r *http.Request, id IdParam)
	// Download order report
	// (GET /reports/orders)
	DownloadOrderReport(w http.ResponseWriter, r *http.Request, params DownloadOrderReportParams)
	// List service categories
	// (GET /service-categories)
	ListServiceCategories(w http.ResponseWriter, r *http.Request, params ListServiceCategoriesParams)
	// Create service category
	// (POST /service-categories)
	CreateServiceCategory(w http.ResponseWriter, r *http.Request)
	// Delete service category
	// (DELETE /service-categories/{id})
	DeleteServiceCategory(w http.ResponseWriter, r *http.Request, id IdParam)
	// Get service category by ID
	// (GET /service-categories/{id})
	GetServiceCategory(w http.ResponseWriter, r *http.Request, id IdParam)
	// Update service category
	// (PUT /service-categories/{id})
	UpdateServiceCategory(w http.ResponseWriter, r *http.Request, id IdParam)
	// List services
	// (GET /services)
	ListServices(w http.ResponseWriter, r *http.Request, params ListServicesParams)
	// Create service
	// (POST /services)
	CreateService(w http.ResponseWriter, r *http.Request)
	// Delete service
	// (DELETE /services/{id})
	DeleteService(w http.ResponseWriter, r *http.Request, id IdParam)
	// Get service by ID
	// (GET /services/{id})
	GetService(w http.ResponseWriter, r *http.Request, id IdParam)
	// Update service
	// (PUT /services/{id})
	UpdateService(w http.ResponseWriter, r *http.Request, id IdParam)
	// List workers
	// (GET /workers)
	ListWorkers(w http.ResponseWriter, r *http.Request, params ListWorkersParams)
	// Create worker
	// (POST /workers)
	CreateWorker(w http.ResponseWriter, r *http.Request)
	// Delete worker
	// (DELETE /workers/{id})
	DeleteWorker(w http.ResponseWriter, r *http.Request, id IdParam)
	// Get worker by ID
	// (GET /workers/{id})
	GetWorker(w http.ResponseWriter, r *http.Request, id IdParam)
	// Update worker
	// (PUT /workers/{id})
	UpdateWorker(w http.ResponseWriter, r *http.Request, id IdParam)
	// Get worker commission aggregates
	// (GET /workers/{id}/commissions/summary)
	GetWorkerCommissionSummary(w http.ResponseWriter, r *http.Request, id IdParam, params GetWorkerCommissionSummaryParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List orders
// (GET /orders)
func (_ Unimplemented) ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create order
// (POST /orders)
func (_ Unimplemented) CreateOrder(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get order aggregates
// (GET /orders/summary)
func (_ Unimplemented) GetOrderSummary(w http.ResponseWriter, r *http.Request, params GetOrderSummaryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get order detail
// (GET /orders/{id})
func (_ Unimplemented) GetOrder(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List payment methods
// (GET /payment-methods)
func (_ Unimplemented) ListPaymentMethods(w http.ResponseWriter, r *http.Request, params ListPaymentMethodsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create payment method
// (POST /payment-methods)
func (_ Unimplemented) CreatePaymentMethod(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete payment method
// (DELETE /payment-methods/{id})
func (_ Unimplemented) DeletePaymentMethod(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get payment method by ID
// (GET /payment-methods/{id})
func (_ Unimplemented) GetPaymentMethod(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update payment method
// (PUT /payment-methods/{id})
func (_ Unimplemented) UpdatePaymentMethod(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download order report
// (GET /reports/orders)
func (_ Unimplemented) DownloadOrderReport(w http.ResponseWriter, r *http.Request, params DownloadOrderReportParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List service categories
// (GET /service-categories)
func (_ Unimplemented) ListServiceCategories(w http.ResponseWriter, r *http.Request, params ListServiceCategoriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create service category
// (POST /service-categories)
func (_ Unimplemented) CreateServiceCategory(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete service category
// (DELETE /service-categories/{id})
func (_ Unimplemented) DeleteServiceCategory(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get service category by ID
// (GET /service-categories/{id})
func (_ Unimplemented) GetServiceCategory(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update service category
// (PUT /service-categories/{id})
func (_ Unimplemented) UpdateServiceCategory(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List services
// (GET /services)
func (_ Unimplemented) ListServices(w http.ResponseWriter, r *http.Request, params ListServicesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create service
// (POST /services)
func (_ Unimplemented) CreateService(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete service
// (DELETE /services/{id})
func (_ Unimplemented) DeleteService(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get service by ID
// (GET /services/{id})
func (_ Unimplemented) GetService(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update service
// (PUT /services/{id})
func (_ Unimplemented) UpdateService(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List workers
// (GET /workers)
func (_ Unimplemented) ListWorkers(w http.ResponseWriter, r *http.Request, params ListWorkersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create worker
// (POST /workers)
func (_ Unimplemented) CreateWorker(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete worker
// (DELETE /workers/{id})
func (_ Unimplemented) DeleteWorker(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get worker by ID
// (GET /workers/{id})
func (_ Unimplemented) GetWorker(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update worker
// (PUT /workers/{id})
func (_ Unimplemented) UpdateWorker(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get worker commission aggregates
// (GET /workers/{id}/commissions/summary)
func (_ Unimplemented) GetWorkerCommissionSummary(w http.ResponseWriter, r *http.Request, id IdParam, params GetWorkerCommissionSummaryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListOrders operation middleware
func (siw *ServerInterfaceWrapper) ListOrders(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrdersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrderSummary operation middleware
func (siw *ServerInterfaceWrapper) GetOrderSummary(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrderSummaryParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrderSummary(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrder operation middleware
func (siw *ServerInterfaceWrapper) GetOrder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrder(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPaymentMethods operation middleware
func (siw *ServerInterfaceWrapper) ListPaymentMethods(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPaymentMethodsParams

	// ------------- Optional query parameter "isActive" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "isActive", r.URL.Query(), &params.IsActive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "isActive", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPaymentMethods(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePaymentMethod operation middleware
func (siw *ServerInterfaceWrapper) CreatePaymentMethod(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePaymentMethod(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePaymentMethod operation middleware
func (siw *ServerInterfaceWrapper) DeletePaymentMethod(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePaymentMethod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPaymentMethod operation middleware
func (siw *ServerInterfaceWrapper) GetPaymentMethod(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPaymentMethod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePaymentMethod operation middleware
func (siw *ServerInterfaceWrapper) UpdatePaymentMethod(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePaymentMethod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadOrderReport operation middleware
func (siw *ServerInterfaceWrapper) DownloadOrderReport(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadOrderReportParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadOrderReport(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListServiceCategories operation middleware
func (siw *ServerInterfaceWrapper) ListServiceCategories(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServiceCategoriesParams

	// ------------- Optional query parameter "isActive" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "isActive", r.URL.Query(), &params.IsActive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "isActive", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListServiceCategories(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateServiceCategory operation middleware
func (siw *ServerInterfaceWrapper) CreateServiceCategory(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateServiceCategory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteServiceCategory operation middleware
func (siw *ServerInterfaceWrapper) DeleteServiceCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteServiceCategory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServiceCategory operation middleware
func (siw *ServerInterfaceWrapper) GetServiceCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServiceCategory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateServiceCategory operation middleware
func (siw *ServerInterfaceWrapper) UpdateServiceCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateServiceCategory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListServices operation middleware
func (siw *ServerInterfaceWrapper) ListServices(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServicesParams

	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "categoryId", r.URL.Query(), &params.CategoryId, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "categoryId", Err: err})
		return
	}

	// ------------- Optional query parameter "isActive" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "isActive", r.URL.Query(), &params.IsActive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "isActive", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListServices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateService operation middleware
func (siw *ServerInterfaceWrapper) CreateService(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateService(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteService operation middleware
func (siw *ServerInterfaceWrapper) DeleteService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteService(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetService operation middleware
func (siw *ServerInterfaceWrapper) GetService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetService(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateService operation middleware
func (siw *ServerInterfaceWrapper) UpdateService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateService(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkers operation middleware
func (siw *ServerInterfaceWrapper) ListWorkers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWorkersParams

	// ------------- Optional query parameter "isActive" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "isActive", r.URL.Query(), &params.IsActive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "isActive", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWorker operation middleware
func (siw *ServerInterfaceWrapper) CreateWorker(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWorker(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWorker operation middleware
func (siw *ServerInterfaceWrapper) DeleteWorker(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWorker(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorker operation middleware
func (siw *ServerInterfaceWrapper) GetWorker(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorker(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWorker operation middleware
func (siw *ServerInterfaceWrapper) UpdateWorker(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWorker(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkerCommissionSummary operation middleware
func (siw *ServerInterfaceWrapper) GetWorkerCommissionSummary(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkerCommissionSummaryParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkerCommissionSummary(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders", wrapper.ListOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders", wrapper.CreateOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders/summary", wrapper.GetOrderSummary)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders/{id}", wrapper.GetOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/payment-methods", wrapper.ListPaymentMethods)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/payment-methods", wrapper.CreatePaymentMethod)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/payment-methods/{id}", wrapper.DeletePaymentMethod)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/payment-methods/{id}", wrapper.GetPaymentMethod)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/payment-methods/{id}", wrapper.UpdatePaymentMethod)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/reports/orders", wrapper.DownloadOrderReport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/service-categories", wrapper.ListServiceCategories)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/service-categories", wrapper.CreateServiceCategory)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/service-categories/{id}", wrapper.DeleteServiceCategory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/service-categories/{id}", wrapper.GetServiceCategory)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/service-categories/{id}", wrapper.UpdateServiceCategory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services", wrapper.ListServices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/services", wrapper.CreateService)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/services/{id}", wrapper.DeleteService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services/{id}", wrapper.GetService)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/services/{id}", wrapper.UpdateService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workers", wrapper.ListWorkers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/workers", wrapper.CreateWorker)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/workers/{id}", wrapper.DeleteWorker)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workers/{id}", wrapper.GetWorker)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/workers/{id}", wrapper.UpdateWorker)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workers/{id}/commissions/summary", wrapper.GetWorkerCommissionSummary)
	})

	return r
}
